### ISSUE TITLE
Why is 'examples' directory excluded as a package in setup.py?

### ISSUE THREAD

**Issue by sgibson91** [devitocodes/devito#1064]
In `setup.py`, the examples directory is excluded from the `find_packages` call. See below.

https://github.com/devitocodes/devito/blob/ea661f98f4a7b59b776ac77a2e4e80ca0dc36b7d/setup.py#L53

Why is this, as this means that the tutorials in `examples/cfd` are no longer executable? See following error from cell1 on `01_convection.ipynb`.

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-0bcda1ec0be4> in <module>
----> 1 from examples.cfd import plot_field, init_hat
      2 import numpy as np
      3 get_ipython().run_line_magic('matplotlib', 'inline')
      4 
      5 # Some variable declarations

ModuleNotFoundError: No module named 'examples'
```

**Comment by mloubout** [comment]
`setup.py` is to install with pip, which is generally for API only install and will install the package inside the python root directory (like /usr/local/Python/....). This kind of install is intended for application that use Devito rather than downloading and running examples.

So to summarise:
- `pip install git+https://github.com/devitocodes/devito` API install (like we install cage/codepy) without example
- `git clone https://github.com/devitocodes/devito; pip install -e .` installl all with examples

**Comment by navjotk** [comment]
To rephrase the above, the first is the user install, the second is the dev install.

**Comment by sgibson91** [comment]
So I asked this question because of the error I quoted. It turns out I was getting that error because the notebook was not loading the correct kernel on launch. Changing the kernel (even though it was reporting that the correct kernel _was_ selected!) removed the error and I can now run code.

I don't know how to begin to debug or fix this problem, but I think it's a fix that needs to go back to Jupyter Notebook, not Devito.

**Comment by navjotk** [comment]
Ok to close this @sgibson91 ?
