### ISSUE TITLE
Streamline dependency management

### ISSUE THREAD

**Issue by tallamjr** [devitocodes/devito#1065]
With `enviroment.yml` some `pip` and `conda` dependencies are defined, but there also exists a separate `requirements.txt`. This is effectively redundant as all dependencies can be contained within the `enviroment.yml` file

**Comment by navjotk** [comment]
Firstly, `environment.yml` defines the development environment. It is the packages you need to develop Devito itself. 

`requirements.txt` is the user environment. The minimum packages you need to be able to install and use Devito.

**Comment by sgibson91** [comment]
Follow up question: Why does the quickstart tutorial instruct user to install the development environment?

**Comment by navjotk** [comment]
@sgibson91 raised an interesting question as to why do we direct people to the conda/ `environment.yml` installation route in the Quickstart even though this is the developer environment and not the user environment.

**Comment by mloubout** [comment]
These are two different objects.

 `environment.yml` is a conda specific file to sept a virtual environment with dependencies including non-pip ones such as conda defaults, python versions, ...

`requirement.txt` is the list of *pip* requirements. One could write a wrapper that reads it and feed it to the `environment.yml` but it is not recommended as some of the pip packages are installed via conda rather than pip in the conda environment.

SO there may be a better way to do it, but not a straightforward one.

**Comment by navjotk** [comment]
Ok let's rephrase the above question. What do we lose if we delete `requirements*.txt` ?

**Comment by mloubout** [comment]
>What do we lose if we delete requirements*.txt ?

No pip install

**Comment by navjotk** [comment]
pip install uses `intall_requires` from `setup.py` anyway?

**Comment by mloubout** [comment]
>pip install uses intall_requires from setup.py anyway?

These are from `requirement.txt`, hard coding dependencies in `setup.py` is doable but better suited for small dependency list, a separate requirement file is more maintainable 

>Or do you mean pip install -r requirements.txt

no I mean `pip install git....`

**Comment by navjotk** [comment]
To summarise, we have the following installation routes, which use the associated requirements lists:
- `pip install git....` uses `requirements.txt`
- `pip install -e .`/`pip install devito` uses `setup.py/install_requires`
- conda -f environment.yml` uses `environment.yml`

Now, onto a best practices discussion with @sgibson91 :)

**Comment by navjotk** [comment]
What do we lose we if we remove `environment.yml`?

**Comment by mloubout** [comment]
The conda environment basically.

**Comment by navjotk** [comment]
What do we need that for? i.e. why don't we just drop it?

**Comment by mloubout** [comment]
the way conda environment work is that it takes what's in the `environment.yml` and install all of it to fixed version so that you have a clean new one with what you need.

**Comment by navjotk** [comment]
I'm saying we don't need that.

**Comment by mloubout** [comment]
>I'm saying we don't need that.

why?

**Comment by navjotk** [comment]
The real question is what I asked above:
> What do we need that for? i.e. why don't we just drop it?

which you answered by explaining how conda works. I know how conda works. Why do we need it - is not answered yet.

**Comment by mloubout** [comment]
Because conda needs it

**Comment by navjotk** [comment]
Why do we need conda?

**Comment by mloubout** [comment]
Because some people use it and want it

**Comment by navjotk** [comment]
We don't need to care about that. People would still be able to install Devito inside conda if Devito had no environment.yml . So what's stopping us from doing that?

**Comment by mloubout** [comment]
you want a Devito environment  not an environment with devito in it

**Comment by navjotk** [comment]
e.g. https://github.com/inducer/cgen has no environment.yml , yet we use it inside conda all the time. Why can't Devito be the same?

**Comment by navjotk** [comment]
> you want a Devito environment not an environment with devito in it

Why?

**Comment by mloubout** [comment]
Because devito has a lot of dependencies that need to be satisfied all, not just one broad one like `cgen`.

**Comment by navjotk** [comment]
What are these dependencies?

**Comment by mloubout** [comment]
everything  in the yaml

**Comment by navjotk** [comment]
The yaml is a repeat of requirements.txt which I'm trying to avoid. Circular logic.

**Comment by navjotk** [comment]
Let's restart the loop from 17 messages ago: 
> What do we lose we if we remove environment.yml?

What is in the environment.yml that is NOT in the requirements.txt? i.e. what do we lose if we remove environment.yml and only live with requirements.txt?

**Comment by mloubout** [comment]
Did some digging, found some options that conda really hid on their doc so didn't think that would work. yaml file can be replaced by 
```
name: devito
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3
  - pip
  - pip:
    - -r file:requirements.txt
```

So that environment still create with proper python and channel but requirements.txt is enough for packages (hopefully)

**Comment by ggorman** [comment]
I think the crux of the issue can be described as:
package A: "you want a foo environment not an environment with foo in it"
package B: "you want a bar environment not an environment with bar in it"

This results in foo no longer being composible with bar.

**Comment by navjotk** [comment]
> you want a Devito environment not an environment with devito in it

I assume you're saying this as a Devito developer and not a Devito user. 

As a user, you want an environment with Devito (AND other stuff) in it, not a Devito environment. See @ggorman 's comment above in case you disagree with this part. 

Assuming we are in agreement that the conda environment is really only useful for Devito developers, we can move forward to my proposal:

- We take up @mloubout 's suggestion above to remove the redundant package list from environment.yml, maybe also add requirements-optional.txt there since the developer environment probably should have mpi/matplotlib
- We rename environment.yml to environment-dev.yml
- We modify the README to have the "recommended user install" towards the top mention the pip route instead of the conda route (this is separate/in addition to the change about making docker the preferred install) - I can offer to do this.
- At the bottom of the README, "Interested in developing for Devito? Perhaps this conda environment will be useful" and only there mention the `conda env` method.

**Comment by mloubout** [comment]
I'm ok with that

**Comment by FabioLuporini** [comment]
@mloubout @navjotk can we close this now?

**Comment by navjotk** [comment]
Yes. Closing
