### ISSUE TITLE
merge devitobench into devito

### ISSUE THREAD

**Issue by FabioLuporini** [devitocodes/devito#1097]
I only see pros, I think

Many assignees because I'm interested in your opinion

I think its not much more than 1 hour legwork (with flake8 and docstring cleanup)

**Comment by mloubout** [comment]
Agreed

**Comment by mloubout** [comment]
#1098

**Comment by georgebisbas** [comment]
Pending : (COPYING @mloubout and @FabioLuporini  from Slack)
Rename class Benchmark into something else. Likewise, rename tools/benchmark.py into something else. Otherwise we have name clashes. Perhaps move to executor.py and rename as ExecutorBatch ? or something to denote the fact that, AFAICT, a current Benchmark instance is supposed to be the “driver” of an Executor instance probably, move make-pbs.py inside /tools

**Comment by mloubout** [comment]
done, closing
