### ISSUE TITLE
sample code has error

### ISSUE THREAD

**Issue by chunhualiao** [devitocodes/devito#1275]
The OpenMP sample code in https://github.com/devitocodes/devito/wiki/OpenMP-5-GPU-offloading-instructions--%5BFabio%5D
```
    #pragma omp target data map(tofrom: x[0:n],y[0:n])
    {
        #pragma omp target
        #pragma omp for
        for (int i = 0; i < n; i++)
            y[i] += a * x[i];
    }
```

I believe the correct one should be

```
    #pragma omp target data map(tofrom: x[0:n],y[0:n])
    {
        #pragma omp target
        #pragma omp parallel for
        for (int i = 0; i < n; i++)
            y[i] += a * x[i];
    }
```
omp for alone won't run things in parallel in GPU. You need omp parallel to start threads.

**Comment by FabioLuporini** [comment]
when I run it -- and I do it only to check up my clang install -- I can clearly see the GPU activity spiking. So, I don't remember what the specs say, but something is surely happening?

**Comment by FabioLuporini** [comment]
@chunhualiao let me also take the opportunity to clarify a couple of aspects. 

That sample code is _not_ devito-generated -- I think I found it on the web somewhere. Something simple enough to quickly check that OpenMP offloading was working.

Also, I just checked the OpenMP 5 specification. AFAICT, the `target` directive (quoting)

```
Map variables to a device data environment and execute the construct on that device
```

in this case, the "device data environment" is the outer `target data`.

So I *think* this isn't a `clang-{9,10,11}` thing, or a buggy sample code, but rather expected behaviour? Am I missing something? If so, can you point me to a page in the specs (or any other documents) to clarify this?

Thanks a lot!

**Comment by chunhualiao** [comment]
My point is that "omp for alone won't run things in parallel in GPU. You need omp parallel to start threads."  What you said is also true. Your code will run things in single thread on GPU. Enough to test offloading. 

![image](https://user-images.githubusercontent.com/1627206/81408984-1ca13100-90f3-11ea-8e8f-f5b31556ec40.png)

**Comment by FabioLuporini** [comment]
oh yes, I agree about that. I'll tweak the example to make things clearer. Thanks!

**Comment by FabioLuporini** [comment]
re-thinking about this -- `parallel` would make the compute too fast, and you may not see any spiking after all, depending on the sampling interval. So I'll leave it as is now.

@chunhualiao , btw, how did you bump into that code sample if I may ask?
