### ISSUE TITLE
gpu_openmp.py shows Unsupported optimization options: [blockinner]

### ISSUE THREAD

**Issue by paklui** [devitocodes/devito#1395]
Hi, I am a new devito user and just trying the pbs_nn1.gen.sh in devito/benchmarks/user. I am also looking for some benchmarks to run for the GPU, and it seems that the benchmarks are not set up for GPU OpenMP offload, the gpu_openmp.py shows that the 'blockinner' optimization is not supported. I just want to find out if it is my configuration, or it is because the benchmarks are not supported yet for GPU. Thanks in advance.
```
  File "/home/devito/devito/devito/core/gpu_openmp.py", line 268, in _normalize_kwargs
    raise InvalidOperator("Unsupported optimization options: [%s]"
devito.exceptions.InvalidOperator: Unsupported optimization options: [blockinner]
```
I tried the CPU test and it appears to be working. I include the files:
[output-cpu-devito-bench-pbs_nn1.gen.txt](https://github.com/devitocodes/devito/files/4928071/output-cpu-devito-bench-pbs_nn1.gen.txt)

GPU test output showing the Unsupported optimization message:
[output-gpu-devito-bench-pbs_nn1.gen.txt](https://github.com/devitocodes/devito/files/4928075/output-gpu-devito-bench-pbs_nn1.gen.txt)

Modified benchmark script:
[pbs_nn1.gen.sh.txt](https://github.com/devitocodes/devito/files/4928073/pbs_nn1.gen.sh.txt)

**Comment by FabioLuporini** [comment]
loop blocking, and therefore all of the blocking related options, isn't applied when on GPU platforms. See [here](https://github.com/devitocodes/devito/blob/master/examples/performance/README.md#optimization-parameters-by-platform)

So the output is as expected, though those pragma warnings suggest there's something off with your offloading compiler

Any other question about benchmarking (on CPUs or GPUs), I suggest we discuss it interactively on slack: https://opesci-slackin.now.sh/ . Alternatively, you may open another issue specifically about benchmarking.  I'm closing this one because I think the original question has been answered
