### ISSUE TITLE
Devito installation on Win10

### ISSUE THREAD

**Issue by Pbottelin** [devitocodes/devito#1410]
Hello everyone,
and thanks for the sharing of such a useful package! I am an applied geophysicist (mostly for landslide hazards, geotechnical stuff, ...) and I wanted to simulate seismic wave propagation for simple media (like in the 2-layer tutorial).

Unfortunately, my machine runs Win10.

I tried several approaches for installation following the guidelines:

1. Conda approach.
I cloned the git deposit, installed devito with pip command.
When I try to run a devito code, I get the error: "DevitoError: could'unt initialize Devito."
I think this might be because my devito install cannot find the gcc compiler?
But in git bash, "which gcc" returns /c/TDM-GCC-64/bin/gcc
Anyway, something goes wrong.

2. Docker approach.
I get the same error as TatianaApril (Issue #1122), which is:
"docker-compose up devito" yields "devito_1  | /usr/bin/env: æbash\rÆ: No such file or directory"

When I try Tatiana's solution, I had to install docker-machine in addition to docker desktop.
"docker-machine start default" yields "Docker machine "default" does not exist."
so I tried
"docker-machine create default" which yields "Error with pre-create check: "VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is in the path"

So I'm pretty stuck here...
Do I have to install a virtual machine with docker-machine?
I thought docker was a kind of VM already.

I hope this may help other win10 users in their installation process.

Thanks for the help,
best regards!

Pierre

**Comment by georgebisbas** [comment]
Hi @Pbottelin , could you try that approach: https://medium.com/@soulfoodpst/install-devito-on-windows-a-tool-for-automatic-programming-3def3949e5c8 ?

**Comment by navjotk** [comment]
I recommend you try the solution George posted above first.

However, if you do want to debug your docker approach, I just want to highlight something:
The error you're seeing happens because of a difference between how Windows and Linux handle line endings in text files. git tries to work around this by automatically replacing line endings as it finds appropriate, however, this breaks docker because now we're running "Linux" (in docker) on files with windows-style line endings. It is important to do what I posted [here](https://github.com/devitocodes/devito/issues/1122#issuecomment-586631681). Why Tatiana moved from using `docker-compose` to `docker-machine` is not clear to me and it may be an issue specific to her environment so I would recommend staying with docker compose unless you know what you are doing.

**Comment by FabioLuporini** [comment]
any progress @Pbottelin ?

**Comment by Pbottelin** [comment]
Hi Fabio, thanks for the reminder. I gave it a last try before leaving for summer holidays.
I succeeded using the link given by @georgebisbas (https://medium.com/@soulfoodpst/install-devito-on-windows-a-tool-for-automatic-programming-3def3949e5c8), i.e. using WSL and conda approach.
I can now run the tutorials in a jupyter notebook :)
Thanks for the help,
cheers
