### ISSUE TITLE
How to use devito to calculate the iso-acoustic wave equation backwards

### ISSUE THREAD

**Issue by Aike886** [devitocodes/devito#1889]
There are a lot of ways to compute the acoustic forward in the tutorial, but if I know the sound field at the last moment, and I know the sound source, then I want to compute the acoustic field backward from the last moment all the way to the first moment.Can devito do it ? I writer an operator,but I got an wrong result after I ran it:

```
from examples.seismic.acoustic import iso_stencil
from examples.seismic import PointSource, Receiver
from devito import Eq, Operator, Function, TimeFunction, Inc, solve, sign
u = TimeFunction(name='u', grid=model.grid, save=None,
                     time_order=2, space_order=4)

src = PointSource(name='src', grid=geometry.grid, time_range=geometry.time_axis,
                      npoint=geometry.nsrc)

rec = Receiver(name='rec', grid=geometry.grid, time_range=geometry.time_axis,
                   npoint=geometry.nrec)

m = model.m

s = model.grid.stepping_dim.spacing
    
eqn_forward = iso_stencil(u, model, 'OT2',forward=False)

src_term = src.inject(field=u.backward, expr=src * s**2 / m)

rec_term=rec.interpolate(expr=u)

op=Operator(eqn_forward + src_term +rec_term , subs=model.spacing_map,
                    name='backward')
```
And I apply it 

```
from examples.seismic.acoustic import AcousticWaveSolver
solver = AcousticWaveSolver(model, geometry, space_order=4)
rec_d,u,_= solver.forward(vp=model.vp)   #last moment acoustic field
src=geometry.src
rec=geometry.rec
op.apply(src=src,grad=grad,u=u,vp=model.vp,dt=geometry.dt)
```
Finally, the result in my rec.data is different from the result in solver.forward's rec_d.data.

Sorry to bother you again. I'd appreciate it if you could help me! This question confuse me a few days

**Comment by mloubout** [comment]
Hi
Yes the wave equation is time-reversible, so in theory if you stop at any time you can time-reverse it and recover the time history. This is completely feasible in Devito. There is however a few points to consider in relation to your example:

- `iso_stencil(..., forward=False)` is not the time-reverse wave equation, it is the adjoint wave-eqauatio. WHile the acoustic WE is self-adjoint the boundary condition is not and this is therefore not equivalent to the time -reverse equation
- AS mentioned in the first point, we ar working with finite domains and therefore boundary conditions. Because of those the equation is not truly reversible and to recover the true time-reverse wavefield, boundary methods are needed where the forward field is saved at the physical oudnary at all time-steps to "memorize" the boundary condition effect

I am not sure I completely follow your examples, but  I would recommend to start with a very simple test case where you implement your own operators rather than rely on our wrapper examples that may not do what you are looking for.

**Comment by Aike886** [comment]
Thanks for your reply. I learned a lot.I have one more question about the `src.inject`. Can I just write the source term into the acoustic wave equation(PDE)? just like :
```
from devito import TimeFunction
from examples.seismic import PointSource, Receiver
from devito import Eq, solve

u = TimeFunction(name="u", grid=model.grid, time_order=2, space_order=4)
src = PointSource(name='src', grid=geometry.grid, time_range=geometry.time_axis,
                      npoint=geometry.nsrc)
pde = model.m * u.dt2 - u.laplace + model.damp * u.dt -src
stencil = Eq(u.backward, solve(pde, u.backward))
```
I can get the same result from the stencil mathematically
And another question is what's the meaning about the  `src.inject(field=u.forward, expr=...)`，I see the field term can be `field=u.forward` and `field=u.backward`，When I want to time-reverse the acoustic WE ,can I just write the following Operator:

```
from devito import TimeFunction
from examples.seismic import PointSource, Receiver
from devito import Eq, solve
u = TimeFunction(name="u", grid=model.grid, time_order=2, space_order=4)

src = PointSource(name='src', grid=geometry.grid, time_range=geometry.time_axis,
                      npoint=geometry.nsrc)

rec = Receiver(name='rec', grid=geometry.grid, time_range=geometry.time_axis,
                   npoint=geometry.nrec)

pde = model.m * u.dt2 - u.laplace + model.damp * u.dt 
stencil = Eq(u.backward, solve(pde, u.backward))

s = model.grid.stepping_dim.spacing

src_term = src.inject(field=u.backward, expr=src * s**2 / model.m)

rec_term=rec.interpolate(expr=u)

op=Operator([stencil] + src_term + rec_term , subs=model.spacing_map)
```

**Comment by FabioLuporini** [comment]
I'll let @mloubout take that question and after that I'll close the issue.

For all these "how-to-use" or "what if" devito questions I recommend using our Slack channel, rather than the issue page here on github, which we use mostly for bugs and feature requests. https://join.slack.com/t/devitocodes/shared_invite/zt-gtd2yxj9-Y31YKk_7lr9AwfXeL2iMFg

**Comment by FabioLuporini** [comment]
any more thoughts about this one?

**Comment by Aike886** [comment]
Thank you！. I already solve this problem

**Comment by mloubout** [comment]
Great to hear, closing.

**Comment by Aike886** [comment]
这是来自QQ邮箱的自动回复邮件。收到！
