### ISSUE TITLE
Check the existence of jit_dir when loading state from pickle

### ISSUE THREAD

**Issue by GlassOfWhiskey** [devitocodes/devito#1981]
In the `save` method of the `Compiler` class, the `sofile` state is written into the compiler's `jit_dir`:
```python
sofile = self.get_jit_dir().joinpath(soname).with_suffix(self.so_ext)
if sofile.is_file():
    ...
else:
    with open(str(sofile), 'wb') as f:
        ...
```
However, since `jit_dir` normally resides into the `tmp` folder, it can not be present anymore when reloading the state from pickle. This is also true when transferring pickled data from one machine to another.
Checking for its existence prior to open the file would be more robust:
```python
sofile = self.get_jit_dir().joinpath(soname).with_suffix(self.so_ext)
if sofile.is_file():
    ...
else:
    if not path.exists(self.get_jit_dir()):
        makedirs(self.get_jit_dir(), exist_ok=True)
    with open(str(sofile), 'wb') as f:
        ...
```

**Comment by FabioLuporini** [comment]
you don't even need the `if not ...` part right? Since there's `exist_ok=True`.

I think I agree

Could you remove the `if`, add a suitable comment, and open a pull request? it would be much appreciated

Note that commit messages should adhere to https://github.com/devitocodes/devito/wiki/Tags-for-commit-messages-and-PR-titles

Thanks
