### ISSUE TITLE
RTM and first arrival

### ISSUE THREAD

**Issue by leilin1995** [devitocodes/devito#2092]
I am following the RTM tutorial using my own velocity model and the RTM produces a layer of very strong signal above the image, but the corresponding position of the velocity model is not a strong impedance interface.  And there are also many shot marks at the very top. Is this related to not removing the first arrival wave? If so, how should I remove the first arrival wave so that the RTM output is not affected by the first arrival wave?
Thank you.

**Comment by mloubout** [comment]
I think that RTM image looks normal, ocean bottom always generates strong events and the points at the top are the expected source artifacts

**Comment by mloubout** [comment]
Well there is a few things you can do
- Mute the water layer in the image. That's the most straightforward and conventional thing to do by just setting the image by hand to zero for every point above the ocean bottom. 
- Do some iterative method like LSRTM instead of RTM to improve the image quality
- Change the imaging condition, for example to something like ISIC (see in https://github.com/slimgroup/JUDI.jl for example)

This RTM image is the base of imaging but usually comes with additional workflows to improve its quality.

**Comment by leilin1995** [comment]
Thank you, I get it.
