### ISSUE TITLE
Revise install instructions

### ISSUE THREAD

**Issue by ggorman** [devitocodes/devito#817]
* Update README.md with revised instillation instructions - docker listed as the first option.
* Add/update troubleshooting section to capture gcc+mac issue, Python version, etc
* ~~Update pipeline tests to test docker on Ubuntu, Mac, Windows.~~ Misguided
* ~~Update Devito instillation documentation under docs to point at README.md (ie enforce single source of truth).~~ Done

**Comment by navjotk** [comment]
The first task on this: "Update pipeline tests to test docker on Ubuntu, Mac, Windows." is on @tmbgreaves

**Comment by tmbgreaves** [comment]
Could you fill me in a bit more on this please? I don't think I entirely understand the question.

Docker ought to be host-independent - ie, the container the tests run in shouldn't have any knowledge of the system the container is running on, and indeed I don't think we get an information about what the host OS is for the Pipelines runs. The container itself as far as I know doesn't have any ability to have Windows or OS X on the inside -- OS X licensing would preclude this as I understand it, and I have no idea how you would implement Windows-in-a-container :-)

**Comment by ggorman** [comment]
Perhaps we are talking past each other. According to https://azure.microsoft.com/en-gb/services/devops/pipelines/ we should be able to "Run in parallel on Linux, macOS and Windows".

**Comment by navjotk** [comment]
> Docker ought to be host-independent - ie, the container the tests run in shouldn't have any knowledge of the system the container is running on

I think the idea is to verify this assumption so that we can s/ought to/is, s/shouldn't/doesn't

**Comment by tmbgreaves** [comment]
> Perhaps we are talking past each other. According to https://azure.microsoft.com/en-gb/services/devops/pipelines/ we should be able to "Run in parallel on Linux, macOS and Windows".

I have no idea how they do that, but will figure it out!

**Comment by tmbgreaves** [comment]
> > Docker ought to be host-independent - ie, the container the tests run in shouldn't have any knowledge of the system the container is running on
> 
> I think the idea is to verify this assumption so that we can s/ought to/is, s/shouldn't/doesn't

If that breaks, Docker is in trouble :-)

**Comment by tmbgreaves** [comment]
Looking into this a bit more, from:

https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml

we can run with either Ubuntu or Windows pools for docker. I'm assuming they're running Docker Enterprise there to allow both to co-exist. What's not clear to me at the moment is how they deal with the duality, as I'd understood one of the key benefits to containers was not having to replicate any of the OS-level processes (in particular, the kernel). I'd thought that to run Docker on Windows you *did* have to replicate the kernel in as much as you ran a Linux VM which then had a single kernel instance for all containers, but a first look at the documentation suggests that's no longer the case and somehow they're running natively -- and somehow can run both linux and windows nodes on the same host.

If that's the case I'm marginally less confident that there wouldn't be any problems switching between them, but only marginally. Docker regularly push the line that the container will never see any difference arising from changing the host, and I would expect any issues that did come up there would be both a docker problem, not a devito problem, and caught well before anything moved into production. Yes, we could test for it, but I think we'd be both needlessly increasing our testing burden and vanishingly unlikely to ever catch a problem.

The option to run a Windows *container* sounds far more useful to Devito, but since I've not run anything in Windows for a long time I would have quite a long spin-up time investing in learning to make it happen. I can do it if there's nobody else with the requisite skills, but I don't use windows anywhere else from a user or service perspective so it would be a fairly expensive single-use investment.

The OS X option appears to be non-container, just installing directly onto the node. I'm marginally more clued up with OS X than Windows but haven't used it in some five or six years and then only as a graphical terminal so would have a fairly steep learning curve again, plus I don't have an OS X system to test on, so it would probably be a lot more efficient to get someone who's installing on OS X already to write a script for pipelines. Again, if there's nobody available I can figure out how to do it but it seems like I would be an inefficient choice of person :)

**Comment by navjotk** [comment]
Ok my earlier understanding might have been mistaken. I think a critical issue is that the docker image we are using for testing is different from the docker image we use for the "recommended install". Can we make it consistent?

**Comment by tmbgreaves** [comment]
I think that's achievable, but needs a little bit of post-testing tweaking -- changing the entrypoint and adding Jupyter in the case of the existing pipelines container.

**Comment by navjotk** [comment]
I understand when you talk about changing the entry point -> the two purposes probably need two different entry points. It is not clear to me whether you think there any other (required) differences between the two?

**Comment by ggorman** [comment]
I've revised the initial issue. In particular I concede that we just want to test with a ubuntu pool and docker should "just work" on other systems (ie we shouldn't have to test that Docker works).

However, user install instructions based on docker should be using a tested docker configuration. Therefore, there is still a strong motivation to having a single tested/trusted docker file rather than the current situation. @tmbgreaves @navjotk can we look at merging these?

**Comment by tmbgreaves** [comment]
Sorry - this got shunted off my list and just realised I haven't replied. I'll look at a merge.

**Comment by tmbgreaves** [comment]
First attempt at this pushed to the dockerfile-merge branch. This is using conda-supplied jupyter, running as a non-root user, and at the moment has the full devito repo exposed to jupyter, which probably needs some trimming -- though still needs to be enough for the full install-test cycle in pipelines.

Some thought may also need to be given to the default build-time parameters in the Dockerfile.

I've tried building this then running examples in the notebook, which seem to run as expected.

Feedback requested :-)

**Comment by georgebisbas** [comment]
Can be related to PR #959.

**Comment by FabioLuporini** [comment]
can we close this now @navjotk @mloubout ?
